### ISSUE TITLE
there are other ETFs as well

### ISSUE THREAD

**Issue by robinarthur** [lokisprogrammer/holy-moley-pred#2]
maybe you can integrate the other 86 ETFs containing GME

There is a list: https://www.etf.com/stock/GME

it would be exciting to see, if the FTD Data match up with the Data from GME or XRT, maybe they rolling it from one ETF to another one from time to time...

**Comment by lokisprogrammer** [comment]
These are actually in there, I just aggregated all of the etf ftds by settlement date for the etfs above
